// Generated by CoffeeScript 1.4.0
(function() {
  var events, processword, stripcomments,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  events = require("events").EventEmitter;

  processword = (function(_super) {

    __extends(processword, _super);

    function processword() {}

    processword.prototype.process = function(words, argv) {
      var processedwords;
      if (argv["argv"]["strip-comments"]) {
        processedwords = stripcomments(words);
        this.processed = true;
        return this.emit("end", processedwords);
      } else {
        this.processed = false;
        return this.emit("end", void 0);
      }
    };

    processword.prototype.processed = function() {
      return this.processed;
    };

    return processword;

  })(events);

  stripcomments = function(words) {
    var each, eachobject, pos, reg, tmpholder, tmpholder2, worddone, wordhaventstrippedblanks, _i, _len;
    tmpholder = [];
    tmpholder2 = words;
    for (_i = 0, _len = tmpholder2.length; _i < _len; _i++) {
      eachobject = tmpholder2[_i];
      each = eachobject["name"];
      pos = each.indexOf("#");
      wordhaventstrippedblanks = pos >= 0 ? each.slice(0, pos) : each;
      reg = /[^ \t].*[^ \t]/g;
      worddone = wordhaventstrippedblanks.match(reg);
      if (worddone && worddone.length !== 0) {
        eachobject["name"] = worddone[0];
        tmpholder.push(eachobject);
      }
    }
    return tmpholder;
  };

  exports.processword = processword;

  exports.stripcomments = stripcomments;

}).call(this);
